// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.Foundation;

namespace Azure_v01
{
	public partial class AppDelegate : NSObject
	{
		public AppDelegate (IntPtr handle) : base (handle)
		{
		}
	}
}
