// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Azure_v01
{
	public partial class Azure_v01ViewController : UIViewController
	{
		public Azure_v01ViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
